### ISSUE TITLE
localytics-react-native runtime configuration

### ISSUE THREAD

**Issue by anutting** [localytics/react-native-template-app#17]
Hi Localytics team,

Please provide an example how I can configure the localytics key at runtime. I would like to load the key from a JavaScript config file for now, and in the future plan to fetch the key from an API. I only see documentation on how to hard code the keys in the native iOS and Android projects, which is not great module design.

Thanks

**Comment by Mriegel** [comment]
HI @anutting 

All of our documentation can be found here: https://docs.localytics.com/dev/react-native.html. If that documentation is not sufficient for you feel free to reach out to our support team at support@localytics.com.  We don't supply a sample for integrating in JS because there are important lifecycle events our SDK needs to latch onto before JS is even loaded. If you were to wait for JS code execution, major features like session tracking and push messaging may be affected.

To follow up on your second question - while it is possible, I would highly encourage you to avoid setting the API key from an API fetch.  Generally speaking, customers who are trying to do this are attempting to integrate our product incorrectly, and have a misunderstanding of what they are trying to achieve.  If you would like to discuss this further with our team, please reach out to support.
